'use client';
import { useState } from 'react';
import { categories, vocabulary } from '@/data/vocabulary';
import type { ProgressState, Word } from '@/types';
import { Icon } from './Icon';
export function Library({records, onStudy}: {records: ProgressState['records']; onStudy: (word: Word) => void}) {
  const [query, setQuery] = useState(''); const [category, setCategory] = useState('all'); const [status, setStatus] = useState('all'); const [page, setPage] = useState(1);
  const filtered = vocabulary.filter(word => (category === 'all' || word.category === category) && (status === 'all' || (records[word.id]?.status || 'unseen') === status) && `${word.word} ${word.translations.join(' ')} ${(word.answerAliases || []).join(' ')}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()));
  const pages = Math.max(1, Math.ceil(filtered.length / 20)); const current = Math.min(page, pages);
  const labels = {known: 'จำได้แล้ว', practice: 'ต้องทบทวน', unseen: 'ยังไม่ได้ลอง'};
  return <section className="library-page"><div className="page-intro"><span className="eyebrow">A WORLD OF WORDS</span><h1>คลังคำศัพท์ของคุณ<span className="accent">.</span></h1><p>400 คำและวลีใน 8 หมวด ค้นพบคำที่อยากใช้ แล้วเริ่มฝึกได้เลย</p></div><div className="library-tools"><label className="search-field"><Icon name="search"/><input type="search" placeholder="ค้นหาคำศัพท์หรือความหมายภาษาไทย…" aria-label="ค้นหาคำศัพท์หรือความหมายภาษาไทย" value={query} onChange={event => {setQuery(event.target.value); setPage(1);}}/></label><select className="library-category" aria-label="หมวดในคลังคำศัพท์" value={category} onChange={event => {setCategory(event.target.value); setPage(1);}}><option value="all">ทุกหมวดหมู่</option>{categories.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select><select className="library-status" aria-label="สถานะคำศัพท์" value={status} onChange={event => {setStatus(event.target.value); setPage(1);}}><option value="all">ทุกสถานะ</option>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div>
    <div className="library-results" role="status">พบ {filtered.length} คำ จากทั้งหมด {vocabulary.length} คำ</div><div className="word-list">{filtered.slice((current - 1) * 20, current * 20).map(word => {const state = records[word.id]?.status || 'unseen'; return <article className="word-row" key={word.id}><div className="library-word"><h2 lang="en">{word.word}</h2><span>{word.partOfSpeech}</span></div><div className="library-meaning"><p>{word.meaning}</p><small>{word.categoryName}</small><div className="library-alternatives">แปลได้ว่า: {word.translations.slice(1).join(' · ')}</div></div><span className={`word-status ${state}`}>{records[word.id]?.score === .5 ? 'เข้าใจบางส่วน · 0.5/1 · ทบทวน' : labels[state]}</span><button className="icon-button" aria-label={`ฝึกคำว่า ${word.word}`} onClick={() => onStudy(word)}><Icon name="arrow"/></button></article>;})}</div>
    {!filtered.length ? <div className="library-empty empty-state"><Icon name="search"/><h2>ยังไม่พบคำที่ค้นหา</h2><p>ลองใช้คำสั้นลง หรือเปลี่ยนหมวดและสถานะ</p><button className="secondary clear-filters" onClick={() => {setQuery(''); setCategory('all'); setStatus('all'); setPage(1);}}>ล้างตัวกรอง</button></div> : <div className="pagination"><button className="secondary previous-page" disabled={current === 1} onClick={() => setPage(current - 1)}>ก่อนหน้า</button><span>หน้า {current} / {pages}</span><button className="secondary next-page" disabled={current === pages} onClick={() => setPage(current + 1)}>ถัดไป <Icon name="arrow"/></button></div>}
  </section>;
}
