import type { CSSProperties } from 'react';
import { vocabulary, categories } from '@/data/vocabulary';
import { study } from '@/lib/study';
import type { ProgressState } from '@/types';
import { Icon } from './Icon';
export function ProgressAside({state, onReview, onProgress}: {state: ProgressState; onReview: () => void; onProgress: () => void}) {
  const counts = study.counts(vocabulary, state.records); const today = state.activity[study.dayKey()] || 0;
  return <aside className="study-aside"><section className="daily-goal panel"><div className="panel-heading"><h2>เป้าหมายวันนี้</h2><span className="small-icon"><Icon name="target"/></span></div><div className="goal-ring" role="img" aria-label={`วันนี้ฝึก ${today} ครั้ง จากเป้าหมาย 20 ครั้ง`} style={{'--progress': `${Math.min(today / 20, 1) * 360}deg`} as CSSProperties}><div><strong>{today}<span>/ 20</span></strong><small>ครั้งที่ฝึกวันนี้</small></div></div><p className="goal-message">{today >= 20 ? 'ถึงเป้าหมายแล้ว เก่งมากเลย!' : today === 0 ? 'คำแรกของวันนี้ รอคุณอยู่' : `อีก ${20 - today} ครั้ง ก็ถึงเป้าหมายแล้ว`}</p><span className="goal-caption">แค่วันละ 20 ครั้ง ค่อย ๆ สะสมความมั่นใจ</span></section><section className="mini-progress panel"><div className="panel-heading"><h2>คำศัพท์ของคุณ</h2><button className="icon-button progress-link" aria-label="ดูความคืบหน้าทั้งหมด" onClick={onProgress}><Icon name="arrow"/></button></div>{(['known','practice','unseen'] as const).map((name, i) => <div key={name} className={`progress-line ${name}`}><span><i/>{['จำได้แล้ว','ต้องทบทวน','ยังไม่ได้ลอง'][i]}</span><strong>{counts[name]} คำ</strong></div>)}<div className="stacked-progress" aria-hidden="true"><span className="known-segment" style={{width: `${counts.known / counts.total * 100}%`}}/><span className="practice-segment" style={{width: `${counts.practice / counts.total * 100}%`}}/></div><button className="review-link" onClick={onReview}><Icon name="repeat"/> ทบทวนคำที่ยังจำไม่ได้ <Icon name="chevron"/></button></section><section className="tip-card"><span><Icon name="bulb"/> LITTLE LEARNING TIP</span><p>ลองพูดคำนั้นออกเสียง<br/>แล้วแต่งประโยคของตัวเอง<br/>สักหนึ่งประโยคดูสิ</p><small>คำเล็ก ๆ ที่ได้ใช้ จะจำได้นานขึ้น</small></section></aside>;
}
export function ProgressPage({state, onPractice}: {state: ProgressState; onPractice: () => void}) {
  const counts = study.counts(vocabulary, state.records); const streak = study.streak(state.activity); const days = study.recentDays(state.activity); const max = Math.max(20, ...days.map(day => day.count));
  const stats = [{icon:'book',label:'คำศัพท์ทั้งหมด',value:400,caption:'คำใน 8 หมวด',color:'blue'}, {icon:'check',label:'จำได้แล้ว',value:counts.known,caption:`${Math.round(counts.known / 4)}% ของคำทั้งหมด`,color:'green'}, {icon:'repeat',label:'ต้องทบทวน',value:counts.practice,caption:'ค่อย ๆ ฝึกอีกครั้งได้เสมอ',color:'orange'}, {icon:'flame',label:'ฝึกต่อเนื่อง',value:streak,caption:'วันติดต่อกัน',color:'purple'}];
  return <section className="progress-page"><div className="page-intro"><span className="eyebrow">YOUR LEARNING JOURNEY</span><h1>ทุกคำที่ฝึก คือความก้าวหน้า<span className="accent">.</span></h1><p>มองย้อนดูสิ่งที่ทำได้ แล้วค่อย ๆ ก้าวต่อในแบบของคุณ</p></div><div className="stats-grid">{stats.map(stat => <div className="stat-card" key={stat.icon}><span className={`stat-icon ${stat.color}`}><Icon name={stat.icon}/></span><span>{stat.label}</span><strong>{stat.value}</strong><small>{stat.caption}</small></div>)}</div><div className="progress-details"><section className="panel weekly-panel"><div className="panel-heading"><h2>จังหวะการเรียนรู้ของคุณ</h2><span>7 วันที่ผ่านมา</span></div><div className="weekly-chart">{days.map((day, i) => <div key={day.key} className={`chart-column ${i === 6 ? 'today' : ''}`} aria-label={`${day.key}: ${day.count} ครั้ง`}><strong>{day.count}</strong><div className="bar-track"><span style={{height: `${Math.max(3, day.count / max * 100)}%`}}/></div><small>{day.label}</small></div>)}</div><p>นับทุกครั้งที่ตรวจคำตอบหรือประเมิน รวมการฝึกคำเดิมซ้ำ</p></section><section className="panel progress-summary"><span className="summary-icon"><Icon name="leaf"/></span><h2>ความสม่ำเสมอ เริ่มที่วันนี้</h2><p>{streak ? `คุณกลับมาฝึกต่อเนื่อง ${streak} วันแล้ว รักษาจังหวะเล็ก ๆ นี้ต่อไปนะ` : 'เริ่มจากคำแรกวันนี้ แล้วพรุ่งนี้กลับมาเจอกันอีกนะ'}</p><button className="primary" onClick={onPractice}>กลับไปฝึกคำศัพท์ <Icon name="arrow"/></button></section></div><section className="panel category-breakdown"><div className="panel-heading"><h2>ความคืบหน้าแต่ละหมวด</h2><span>อิงจากคำที่จำได้ล่าสุด</span></div><div className="breakdown-list">{categories.map(category => {const count = study.counts(vocabulary.filter(w => w.category === category.id), state.records); return <div key={category.id} className="breakdown-row" style={{'--category-color': category.color} as CSSProperties}><span className="category-icon"><Icon name={category.icon}/></span><div className="breakdown-name"><strong>{category.name}</strong><small>{category.english}</small></div><div className="breakdown-track"><span style={{width: `${count.known / count.total * 100}%`}}/></div><span>{count.known}/{count.total} คำ</span></div>;})}</div></section></section>;
}
